version: 0.0
os: linux
files:
  - source: /codedeploy/index.php
    destination: /var/www/html/
  - source: /codedeploy/default.conf
    destination: /etc/nginx/conf.d/
hooks:
  BeforeInstall:
    - location: codedeploy/install_dependencies
      timeout: 300
      runas: root
    - location: codedeploy/stop_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/start_server
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: codedeploy/start_server
      timeout: 300
      runas: root

