branch-defaults:
  default:
    environment: null
global:
  application_name: help
  default_ec2_keyname: ../stelligent-demo-20150512005231
  default_platform: docker
  default_region: us-west-2
  profile: null
  sc: null
